version: '3'
services:
  dice-openresty:
    container_name: dice-openresty
    build:
      context: ./
      dockerfile: ./dice-docker/dice-openresty/openresty-prod
    environment:
      TZ: Asia/Shanghai
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ~/.dice/logs/openresty:/usr/local/openresty/nginx/logs
    depends_on:
    - dice-server
    - dice-front
    networks:
      dice-net:
        ipv4_address: 172.28.1.1

  dice-mysql:
    container_name: dice-mysql
    build:
      context: ./
      dockerfile: ./dice-docker/dice-mysql/dice-mysql-Dockerfile
    environment:
      MYSQL_DATABASE: dice
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    expose:
    - "3306"
    volumes:
    - ~/.dice/mysql/mysql_data:/var/lib/mysql
    restart: always
    command:
    - --character-set-server=utf8mb4
    - --default-authentication-plugin=mysql_native_password
    networks:
      dice-net:
        ipv4_address: 172.28.1.2

  dice-server:
    container_name: dice-server
    build:
      context: ./
      dockerfile: ./dice-docker/dice-server-Dockerfile
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
    volumes:
    - ~/.dice/logs/server:/app/logs
    - ~/.dice/upload:/root/.dice/upload
    expose:
    - "9091"
    command: java -jar dice.jar
    depends_on:
    - dice-mysql
    - dice-redis
    restart: always
    networks:
      dice-net:
        ipv4_address: 172.28.1.3

  dice-redis:
    container_name: dice-redis
    build:
      context: ./
      dockerfile: ./dice-docker/dice-redis-Dockerfile
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      dice-net:
        ipv4_address: 172.28.1.4

  dice-front:
    container_name: dice-front
    build:
      context: ./
      dockerfile: ./dice-docker/dice-front/dice-front-Dockerfile
    environment:
      TZ: Asia/Shanghai
    entrypoint: /app/entrypoint.sh -d dice-server:9091 -c 'npm run start';
    expose:
    - "3000"
    depends_on:
    - dice-server
    networks:
      dice-net:
        ipv4_address: 172.28.1.6

networks:
  dice-net:
      ipam:
          driver: default
          config:
              - subnet: 172.28.0.0/16
